import pandas as pd
import matplotlib.pyplot as plt
df = pd.read_csv("Sample - Superstore.csv.csv",encoding="cp1252")
print("First 5 rows:\n", df.head())
print("\nDataset Info:\n")
print(df.info())
print(df.columns)
print("\nSummary Stats:\n", df.describe())
print("\nMissing Values:\n", df.isnull().sum())
print("\nCategory Counts:\n", df['Category'].value_counts())
print("\nRegion Counts:\n", df['Region'].value_counts())
df=df.dropna()
sales_by_category = df.groupby('Category')['Sales'].sum().reset_index()
profit_by_region = df.groupby('Region')['Profit'].sum().reset_index()
print("\nSales by Category:\n", sales_by_category)
print("\nProfit by Region:\n", profit_by_region)
df=df.drop_duplicates()
top_products = (
    df.groupby('Product Name')['Sales']
    .sum()
    .sort_values( ascending=False)
    .head(10)
)
print("\nTop 10 Products by Sales:\n", top_products)
plt.title("Total Sales by Category")
category_sales=df.groupby("Category")["Sales"].sum()
plt.bar(category_sales.index,category_sales.values)
plt.xlabel("Category")
plt.ylabel("Sales")
plt.show()
plt.title("Total Profit by Region")
region_profit=df.groupby("Region")["Profit"].sum()
plt.bar(region_profit.index,region_profit.values)
plt.xlabel("Region")
plt.ylabel("Profit")
plt.xticks(rotation=90)
plt.show()
sales_by_category.to_csv("sales_by_category.csv", index=False)
profit_by_region.to_csv("profit_by_region.csv", index=False)
df.to_csv("cleaned_sample_superstore.csv.csv",index=False)